# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcoreCli < Formula
  desc "The official Gcore CLI"
  homepage "https://github.com/G-Core/gcore-cli"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.2.0/gcore-cli_darwin_amd64"
      sha256 "fc5ebd0abba198fad7ecc67601591a368a22fbbb2a6ea68330bb2c8b263df14d"

      def install
        bin.install "gcore-cli_darwin_amd64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.2.0/gcore-cli_darwin_arm64"
      sha256 "4a6d7d10bf77019b41fb17596e454209f713176afa9f62c7e0244f24802007f6"

      def install
        bin.install "gcore-cli_darwin_arm64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.2.0/gcore-cli_linux_amd64"
      sha256 "6edaf148ad6606483647ffab2f5409d8ab7e1db963c58a5eeafd240eddd593b1"

      def install
        bin.install "gcore-cli_linux_amd64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.2.0/gcore-cli_linux_arm64"
      sha256 "c5bd8cc797540d4e40f3044b47da5172656bad9d6df3a7219d3166eb3793b8a0"

      def install
        bin.install "gcore-cli_linux_arm64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
  end
end
