# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GcoreCli < Formula
  desc "The official Gcore CLI"
  homepage "https://github.com/G-Core/gcore-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.1.1/gcore-cli_darwin_amd64"
      sha256 "c1fcff5dfd9bd6719f1d223123964f35d5d6dfe299aa476b4d370f248012eeed"

      def install
        bin.install "gcore-cli_darwin_amd64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.1.1/gcore-cli_darwin_arm64"
      sha256 "17292bfefebb4420ff3502b6c9f04538ceeb5228755f4975e07f1863dcc00042"

      def install
        bin.install "gcore-cli_darwin_arm64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.1.1/gcore-cli_linux_amd64"
      sha256 "7568abd8b613cbda6d8385eb6ad05402a86a5a5b687a38be0c9490395cea7930"

      def install
        bin.install "gcore-cli_linux_amd64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/g-core/gcore-cli/releases/download/v0.1.1/gcore-cli_linux_arm64"
      sha256 "05d31041a7bc853e93ea769c6be90918ce35c648d9f729cfb034bd635e08ae15"

      def install
        bin.install "gcore-cli_linux_arm64" => "gcore-cli"
        chmod 0555, bin/"gcore-cli"
        generate_completions_from_executable(bin/"gcore-cli", "completion")
      end
    end
  end
end
